### ISSUE TITLE
using this plugin with Angular 15

### ISSUE THREAD

**Issue by pedromoto4** [artus9033/chartjs-plugin-dragdata#121]
**Describe the bug**
I cant add this plugin data in the ChartOptions structure
I receive this error.
I'm not sure if im doing this the right way but I hope anyone can help me, the true is that to angular 15 with this plugin I cant find any example :/
<img width="760" alt="Captura de ecrã 2023-04-28, às 02 04 00" src="https://user-images.githubusercontent.com/1482801/235029999-b8897142-7081-4ad0-9cb5-530c9f9eb130.png">

**this is my package** 
    "@angular/animations": "^15.2.0",
    "@angular/common": "^15.2.0",
    "@angular/compiler": "^15.2.0",
    "@angular/core": "^15.2.0",
    "@angular/forms": "^15.2.0",
    "@angular/platform-browser": "^15.2.0",
    "@angular/platform-browser-dynamic": "^15.2.0",
    "@angular/router": "^15.2.0",
    "chart.js": "^3.9.1",
    "chartjs-plugin-dragdata": "^2.2.5",
    "ng2-charts": "^4.1.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
**the html**
    <canvas baseChart width="400" height="400"
      [type]="'line'"
      [data]="lineChartData"
      [options]="lineChartOptions"
      [legend]="lineChartLegend">
    </canvas>

**xyz.component.ts**
import { Component } from '@angular/core';
import { ChartConfiguration, ChartOptions, ChartType } from "chart.js";
import 'chartjs-plugin-dragdata' ;

@Component({
  selector: 'app-xyz',
  templateUrl: './xyz.component.html',
  styleUrls: ['./xyz.component.scss']
})
export class XyzComponent {

  title = 'ng2-charts-demo';

  public lineChartData: ChartConfiguration<'line'>['data'] = {
    labels: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July'
    ],
    datasets: [
      {
        data: [ 65, 59, 80, 81, 56, 55, 40 ],
        label: 'Series A',
        fill: true,
        tension: 0.5,
        borderColor: 'black',
        backgroundColor: 'rgba(255,0,0,0.3)',
      }
    ]
  };

  
  public lineChartOptions: ChartOptions<'line'> = {
    responsive: false,
    plugins:{
      dragData: {
        round: 1,
        showTooltip: true,
        onDragStart: function(e) {
          // console.log(e)
        },
        onDrag: function(e, datasetIndex, index, value) {              
          e.target.style.cursor = 'grabbing'
          if (value < 0) return false
          // console.log(e, datasetIndex, index, value)
        },
        onDragEnd: function(e, datasetIndex, index, value) {
          e.target.style.cursor = 'default' 
          // console.log(datasetIndex, index, value)
        },
      }
    }
  };
  public lineChartLegend = true;

  constructor( ){
  }
}

**Comment by CSorel-Catalyte** [comment]
Did you find a solution to this? I'm having the same issue.

**Comment by artus9033** [comment]
@pedromoto4 @CSorel-Catalyte this issue originates from a lack of proper typings - the global chart.js's typings need to be augmented to accept the plugin's configuration. Migration to TS (which is going to happen in the near future) will solve this.

**Comment by death7654** [comment]
is this issue resolved?

**Comment by Megaemce** [comment]
The issue is not sorted as the TypeScript version is still not online. 
My way around this issue is like so:

````ts
import { ChartOptions } from "chart.js";

type RadarOptionsType = ChartOptions<"radar"> & {
    plugins?: {
        dragData?: {
            round?: number;
            showTooltip?: boolean;
            onDragStart?: (e: MouseEvent, element: any) => boolean | void;
            onDrag?: (
                e: MouseEvent,
                datasetIndex: number,
                index: number,
                value: number
            ) => boolean | void;
            onDragEnd?: (e: MouseEvent) => void;
        };
    };
};

const options: RadarOptionsType = {
    layout: {
        // layout options here
    },
    scales: {
       // scale options here
    },
    plugins: {
        // other plugins options here
        dragData: {
            round: 0,
            showTooltip: false,
            onDragStart: (e: MouseEvent, element: any) => { // onDragStart body here }
            onDrag: (e: MouseEvent, datasetIndex: number, index: number, value: number) => { //onDrag body here }
            onDragEnd: (e: MouseEvent) { // onDragEnd body here },
        },
    },
    // other options here
};
````

and then 

````ts
import { Radar } from "react-chartjs-2";

// you can add all the props that you use within your chart/project
type ChartDataType = {
    labels: string[];
    datasets: {
        label: string;
        data: number[];
        backgroundColor?: string;
        borderColor?: string;
        pointBackgroundColor?: string;
        pointBorderColor?: string;
        pointRadius?: number;
        borderWidth?: number;
        pointBorderWidth?: number;
        pointHoverRadius?: number;
        fill?: boolean;
        zIndex?: number;
        datalabels?: {
            display: boolean;
        };
    }[];
};

interface RadarProps {
    data: ChartDataType;
    options: RadarOptionsType;
}

<Radar data={data} options={options} />;

````


![image](https://github.com/user-attachments/assets/47accd7b-dd21-439f-a3d2-17e2c6afa554)
