### ISSUE TITLE
Roadmap for v2.3.0 and near future 📣

### ISSUE THREAD

**Issue by artus9033** [artus9033/chartjs-plugin-dragdata#131]
Hey everyone 👋

It has been a while and the plugin requires some improvements to be applied, as you reported in the issues. I have planned a list of issues that resolved will constitute for a v2.3.0 (due to large changes everywhere) update and a few more plans for the near future.

The new version will definitely carry - first - [the tests](https://github.com/chrispahm/chartjs-plugin-dragdata/issues/40) that the current branch shall be passing. This way we will unblock an easier, much more automated, way to introduce new changes from now on.
This will enable us to implement the rewrite in TypeScript I prepared a while ago. After that is merged and passes all tests for the current version, we will move on to fixing bugs that still appear green on the issues list 🟢 

Finally, after the above is done, a crucial thing for the library will be a new touch to the documentation. Most likely we will leverage Docusaurus to do that and will auto-generate documentation, also making use of the current samples that are in `docs`.

Check the [v2.3.0 milestone](https://github.com/chrispahm/chartjs-plugin-dragdata/milestone/1) and stay tuned for updates 🔧

**Comment by ashley-mort** [comment]
Will the current dragdata plugin work on Chart.js 4?

**Comment by fotoflo** [comment]
Amazing to hear @artus9033!  Congratulations and looking forward to huge success for you and this project.

Quick note that all the demos on @chrispahm's  chrispahm.github.io appear to be 404s.  As a new user planning to implement a drag drop, I was really hoping to see a working demo of the single y-axis to make sure it's exactly what I was looking to achieve.  I will check the JS fiddle demos more carefully... and perhaps email you :-)

**Comment by artus9033** [comment]
Thanks @fotoflo ! Sure, I am aware of that, but have had a pretty extensive time recently. I'm jumping into these topics today and will start with fixing the README 👨‍💻

**Comment by artus9033** [comment]
@fotoflo the issue was fixed in #133

**Comment by artus9033** [comment]
Due to enormous changes almost everywhere, finally this milestone will be released as v3.0.0.
