### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by chrispahm** [artus9033/chartjs-plugin-dragdata#40]
Re-occuring issues as https://github.com/chrispahm/chartjs-plugin-dragdata/issues/39 show that this plugin is in need of some well defined tests. 

The tests should cover
  - dragging on all types of charts is working
  - dragging on stacked charts is working
  - dragging to 0 is working
  - the callbacks are provided with the correct function arguments
  - rounding of values is working correct
  - `dragData: false` within a dataset is working as expected
  - touch device support

Did I forget something? I will try my best to review open PRs, and get started with writing these tests in the coming weeks. However, help would be greatly appreciated!

**Comment by artus9033** [comment]
Since the tests introduced in #132, #97, #120, #140 and the coverage level reported in codecov is $\approx 90\\%$, this issue can 
now be closed 🎉
